---
title: "Coding_with_R"
author: "HibaBenAribi"
date: "2024-04-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r dependencies}
#install package
install.packages("lubridate")
#call package
library(lubridate)
```

```{r }
#  1. Get current year
current_year <- year(Sys.Date())
current_year
## OR
## 2.  Run
current_year <- 2024
current_year
```

```{r }
# 1. Get year of birth from user input
year_of_birth <- as.integer(readline(prompt = "Enter your year of birth: "))

## OR
#2. Run
year_of_birth <- 2010
year_of_birth
```


```{r }
# Calculate age
age <- current_year - year_of_birth
age
```

```{r }
# Check age and display message
if (year_of_birth == current_year) {
  cat("You were born this year.\n")
} else if (current_year == year_of_birth + 1) {
  cat("You are", age, "year old.\n")
} else if (current_year > year_of_birth) {
  cat("You are", age, "years old.\n")
} else if (current_year + 1 == year_of_birth) {
  cat("You will be born in", abs(age), "year.\n")
} else {
  cat("You will be born in", abs(age), "years.\n")
}
```
