---
title: "Introduction_to_R_coding"
author: "HibaBenAribi"
date: "2024-04-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
#define a variable
 # Letter
a <- "A"
#Number 
b <- 1 
#print
print(a)
print(b)
```
## Simple operations

```{r Addition}
# Addition
a <- c (1, 0.1)
b <- c (2.33, 4)
print (a+b)

```
```{r Subtraction }
#Subtraction 
 a <- 6
 b <- 8.4
 print (a-b)

```
```{r Multiplication }
# Multiplication
B= c(4,4) 
C= c(5,5)
print (B*C)

```
```{r Division}
#Division
 a <- 10
 b <- 5
 print (a/b)

```
```{r Power}
# Power
 a <- 4
 b <- 5
 print(a^b)

```
## If 
```{r }
# If operation
x <- 5 

# Check value is less than or greater than 10 
if(x > 10) 
{ 
	print(paste(x, "is greater than 10")) 
} else
{ 
	print(paste(x, "is less than 10")) 
} 
```

```{r }
# while loop
# R program to demonstrate the use of while loop 

val = 1 

# using while loop 
while (val <= 5 ) 
{ 
	# statements 
	print(val) 
	val = val + 1 
} 
```

```{r }
# using for loop  
for (val in 1:5)  
{  
    # statement  
    print(val)  
} 

```

```{r }
# For 
  
val <- 6:11 
  
# Loop  
for (i in val)  
{  
    if (i == 8)  
    {  
        # test expression  
        next
    }  
    print(i)  
}  
```

```{r }

```

```{r }

```

```{r }

```

```{r }

```

